#!/bin/sh /etc/rc.common
# Copyright (C) 2013-2014 OpenWrt.org
# shellcheck disable=SC3043,SC2034

START=00
STOP=90

RTC_DEV=/dev/rtc0
HWCLOCK=/sbin/hwclock

boot() {
	start && exit 0

	local curtime maxtime
	maxtime="$(maxtime)"
	curtime="$(date +%s)"
	[ "$curtime" -lt "$maxtime" ] && date -s "@$maxtime"
}

start() {
	[ -e "$RTC_DEV" ] && [ -x "$HWCLOCK" ] && "$HWCLOCK" -s -u -f "$RTC_DEV"
}

stop() {
	[ -e "$RTC_DEV" ] && [ -x "$HWCLOCK" ] && "$HWCLOCK" -w -u -f "$RTC_DEV" &&
		logger -t sysfixtime "saved '$(date)' to $RTC_DEV"
}

maxtime() {
	local newest
	# redirect to /dev/null to suppress message "terminated by signal 13"
	newest="$(find /etc -type f -print0 | xargs -0 ls -1 -t 2>/dev/null | head -1)"
	[ -z "$newest" ] || date -r "$newest" +%s
}
