#!/bin/sh /etc/rc.common
# Copyright (C) 2013-2014 OpenWrt.org
# shellcheck disable=SC3043,SC2034

START=00
STOP=90

RTC_DEV=/dev/rtc0
HWCLOCK=/sbin/hwclock

boot() {
	hwclock_load
	local curtime maxtime
	maxtime="$(find_max_time)"
	curtime="$(date +%s)"
	if [ $curtime -lt $maxtime ]; then
		date -s @$maxtime
		hwclock_save
	fi
}

start() {
	hwclock_load
}

stop() {
	hwclock_save
}

hwclock_load() {
	[ -e "$RTC_DEV" ] && [ -x "$HWCLOCK" ] && "$HWCLOCK" -s -u -f "$RTC_DEV"
}

hwclock_save(){
	[ -e "$RTC_DEV" ] && [ -x "$HWCLOCK" ] && "$HWCLOCK" -w -u -f "$RTC_DEV" &&
		logger -t sysfixtime "saved '$(date)' to $RTC_DEV"
}

find_max_time() {
	local newest
	# redirect to /dev/null to suppress message "terminated by signal 13"
	newest="$(find /etc -type f -print0 | xargs -0 ls -1 -t 2>/dev/null | head -1)"
	[ -z "$newest" ] || date -r "$newest" +%s
}
