#!/bin/sh
# Copyright (C) 2006-2016 OpenWrt.org

export HOTPLUG_TYPE="$1"

. /lib/functions.sh

PATH="%PATH%"
LOGNAME=root
USER=root
export PATH LOGNAME USER
export DEVICENAME="${DEVPATH##*/}"

if [ -n "$1" ] && [ -d "/etc/hotplug.d/$1" ]; then
	for script in "/etc/hotplug.d/$1"/*; do
		[ -f "$script" ] || continue
		(. "$script")
	done
fi
