#!/bin/sh
# shellcheck disable=SC2039

main() {
	local service="$1"
	shift

	if [ -f "/etc/init.d/$service" ]; then
		"/etc/init.d/$service" "$@"
		exit $?
	fi

	if [ -n "$service" ]; then
		echo "Service \"$service\" not found:"
		exit 1
	fi

	echo "Usage: ${0##*/} <service> [command]"
	for service in /etc/init.d/*; do
		local name="${service##*/}"
		local boot
		if "$service" enabled; then boot=enabled; else boot=disabled; fi
		printf "%-30s\t%10s\t%10s\n" "$service" "$boot" \
			"$([ "$(ubus call service list "{ \"verbose\": true, \"name\": \"$name\" }" |
				jsonfilter -q -e "@[\"$name\"].instances[*].running" | uniq)" = true ] &&
				echo running || echo stopped)"
	done
}

main "$@"
